MongoDB shell version v4.4.6
connecting to: mongodb://127.0.0.1:27017/nbd?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("92ad0fc2-9216-4908-8e22-d3f78f075a2c") }
MongoDB server version: 4.4.6
{
	"zawody" : [
		"Information Systems Manager",
		"Accountant IV",
		"Software Test Engineer IV",
		"Paralegal",
		"Administrative Assistant III",
		"Software Engineer IV",
		"Recruiter",
		"Compensation Analyst",
		"Account Executive",
		"Financial Advisor",
		"Systems Administrator IV",
		"Financial Analyst",
		"Web Developer I",
		"Accounting Assistant III",
		"Budget/Accounting Analyst III",
		"Web Developer II",
		"Web Designer III",
		"Business Systems Development Analyst",
		"Marketing Assistant",
		"Nurse",
		"Quality Control Specialist",
		"Accountant II",
		"Geologist IV",
		"Environmental Tech",
		"VP Sales",
		"Accounting Assistant I",
		"Staff Accountant II",
		"Legal Assistant",
		"Design Engineer",
		"Office Assistant II",
		"Pharmacist",
		"Speech Pathologist",
		"Payment Adjustment Coordinator",
		"Research Assistant IV",
		"Structural Analysis Engineer",
		"Administrative Assistant I",
		"Health Coach I",
		"Structural Engineer",
		"Health Coach II",
		"Developer III",
		"Senior Editor",
		"Chemical Engineer",
		"Marketing Manager",
		"Web Designer I",
		"Web Developer IV",
		"Administrative Officer",
		"Developer I",
		"Geologist III",
		"Account Representative IV",
		"Budget/Accounting Analyst II",
		"Database Administrator II",
		"Human Resources Assistant IV",
		"Programmer Analyst IV",
		"Office Assistant III",
		"Systems Administrator III",
		"Senior Cost Accountant",
		"Account Coordinator",
		"Quality Engineer",
		"Geologist II",
		"Graphic Designer",
		"Programmer Analyst II",
		"Safety Technician II",
		"Data Coordiator",
		"Software Consultant",
		"Environmental Specialist",
		"Programmer III",
		"VP Product Management",
		"Operator",
		"Budget/Accounting Analyst IV",
		"Database Administrator I",
		"Assistant Professor",
		"Database Administrator III",
		"VP Marketing",
		"Geologist I",
		"Senior Developer",
		"Senior Quality Engineer",
		"Product Engineer",
		"Actuary",
		"Software Engineer I",
		"Senior Sales Associate",
		"Social Worker",
		"Technical Writer",
		"Developer II",
		"Staff Accountant IV",
		"Media Manager IV",
		"Teacher",
		"Nuclear Power Engineer",
		"Office Assistant IV",
		"VP Quality Control",
		"Safety Technician I",
		"Media Manager I",
		"GIS Technical Architect",
		"Health Coach IV",
		"Automation Specialist III",
		"Administrative Assistant II",
		"Software Engineer II",
		"Civil Engineer",
		"Geological Engineer",
		"Account Representative II",
		"Engineer I",
		"Software Test Engineer II",
		"Physical Therapy Assistant",
		"Staff Scientist",
		"Programmer II",
		"Media Manager II",
		"Statistician IV",
		"Assistant Media Planner",
		"Executive Secretary",
		"Web Developer III",
		"Programmer IV",
		"VP Accounting",
		"Systems Administrator I",
		"Safety Technician III",
		"Sales Associate",
		"Occupational Therapist",
		"Software Test Engineer I",
		"Mechanical Systems Engineer",
		"Junior Executive",
		"Administrative Assistant IV",
		"Computer Systems Analyst IV",
		"Research Assistant III",
		"Media Manager III",
		"Tax Accountant",
		"Project Manager",
		"Senior Financial Analyst",
		"Internal Auditor",
		"Database Administrator IV",
		"Accountant III",
		"Automation Specialist I",
		"Biostatistician I",
		"Associate Professor",
		"General Manager",
		"Statistician III",
		"Engineer III",
		"Web Designer IV",
		"Safety Technician IV",
		"Office Assistant I",
		"Web Designer II",
		"Engineer IV",
		"Electrical Engineer",
		"Nurse Practicioner",
		"Chief Design Engineer",
		"Registered Nurse",
		"Human Resources Assistant I",
		"Account Representative I",
		"Software Test Engineer III",
		"Computer Systems Analyst I",
		"Statistician II",
		"Research Assistant I",
		"Dental Hygienist",
		"Computer Systems Analyst II",
		"Desktop Support Technician",
		"Research Associate",
		"Budget/Accounting Analyst I",
		"Help Desk Operator",
		"Professor",
		"Accounting Assistant II",
		"Developer IV",
		"Engineer II",
		"Editor",
		"Librarian",
		"Systems Administrator II",
		"Recruiting Manager",
		"Biostatistician III",
		"Human Resources Assistant III",
		"Community Outreach Specialist",
		"Programmer Analyst I",
		"Accountant I",
		"Biostatistician II",
		"Staff Accountant III",
		"Automation Specialist IV",
		"Sales Representative",
		"Human Resources Assistant II",
		"Biostatistician IV",
		"Health Coach III",
		"Staff Accountant I",
		"Computer Systems Analyst III",
		"Account Representative III",
		"Help Desk Technician",
		"Cost Accountant",
		"Programmer I",
		"Research Nurse",
		"Automation Specialist II",
		"Analog Circuit Design manager",
		"Software Engineer III",
		"Clinical Specialist",
		"Assistant Manager",
		"Research Assistant II",
		"Director of Sales",
		"Human Resources Manager",
		"Food Chemist",
		"Accounting Assistant IV",
		"Statistician I",
		"Programmer Analyst III",
		"Analyst Programmer"
	]
}
